config/routes.rb
Rails.application.routes.draw do
  resources :overlay

  get '/profile', to: 'overlay#profile'
  get '/publish', to: 'overlay#publish'
  get '/download', to: 'overlay#download'
  get '/privacy', to: 'overlay#privacy'
  get 'auth/facebook', as: 'auth_provider'
  get 'auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'overlay#index'

end

app/models/overlay.rb
class Overlay
  def self.images
    %w(dashain.png dashain2.png npflag.png dharahara.png merodesh.png ilovenepal.png)
  end

  def self.create_image source, overlay_image, user
    source = source.resize_to_fill(500, 500)
    file = "#{user.uid}_#{overlay_image}"

    overlay = Magick::Image.read("app/assets/images/overlays/#{overlay_image}").first
    temp = source.composite(overlay, Magick::CenterGravity, Magick::SrcOverCompositeOp)
    temp.opacity = (Magick::TransparentOpacity-Magick::OpaqueOpacity) * 0.45
    source.composite!(temp, Magick::CenterGravity, Magick::SrcOverCompositeOp)
    s3_upload source, file
  end

  def self.get_source_image user
    source = Magick::ImageList.new
    image_url = URI.parse(user[:image_url])
    image_url.scheme = 'https'
    urlimage = open(image_url)
    source.from_blob(urlimage.read).first
  end

  def self.s3_upload source, file
    s3 = Aws::S3::Resource.new(
            region:'us-east-1',
            credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'],
                                          ENV['AWS_SECRET_ACCESS_KEY']))
    bucket = s3.bucket(ENV['S3_BUCKET_NAME'])
    bucket.object(file).put({body: source.to_blob, acl: 'public-read'})
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, :name, :image_url, presence: true

  def self.from_omniauth(auth_hash)
    # raise auth_hash['provider'].inspect
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.uid = auth_hash['uid']
    user.name = auth_hash['info']['name']
    user.image_url = auth_hash['info']['image']
    user.token = auth_hash['credentials']['token']
    user.save!
    user
  end

  def delete_images
    images = Overlay.images
    images.map! { |image| "#{uid}_#{image}" }
    s3 = Aws::S3::Resource.new(
            region:'us-east-1',
            credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'],
                                          ENV['AWS_SECRET_ACCESS_KEY']))
    bucket = s3.bucket(ENV['S3_BUCKET_NAME'])
    bucket.objects.delete(images)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    helper_method :current_user
end

app/controllers/overlay_controller.rb
require 'open-uri'
class OverlayController < ApplicationController
  after_filter :allow_iframe_requests
  before_filter :require_login, except: [:index, :privacy]
  before_filter :fetch_image, only: [:publish, :download]

  def index
    if current_user
      redirect_to profile_path
    end
  end

  def profile
    source = Overlay.get_source_image current_user
    @overlay_images = Overlay.images
    @overlay_images.each do |overlay|
      Overlay.create_image source, overlay, current_user
    end
  end

  def publish
    facebook = Koala::Facebook::API.new(current_user.token)
    img = facebook.put_picture(@file_path, {}, "me")
    url = "https://www.facebook.com/photo.php?fbid=#{img['id']}&makeprofile=1"

    redirect_to url
  end

  def privacy
  end

  def download
    data = open(@file_path)
    send_file data, filename: "profile_pic.jpg", type: "image/jpeg", disposition: 'attachment'
  end

  def allow_iframe_requests
    response.headers.delete 'X-Frame-Options'
  end

  private
    def fetch_image
      image = params.fetch(:image) if params[:image]
      url = 'https://s3.amazonaws.com/profile-overlay-assets'
      @file_path = "#{url}/#{current_user.uid}_#{image}.png"
    end

    def require_login
      redirect_to root_path unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end
    redirect_to profile_path
  end

  def destroy
    if current_user
      current_user.delete_images
      session.delete(:user_id)
      flash[:success] = 'Successfully logged out!'
    end
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="col-md-12 col-sm-12 col-xs-12">
    Copyright &copy; 2016. All Rights Reserved. Developed with
    <span class="glyphicon glyphicon-heart"></span> by
    <a href="https://www.facebook.com/laalu" target="_blank">Lal Saud</a>.
    Source code shared @
    <a href="https://github.com/lalusaud/profile_overlay" target="_blank">Github</a>.
    Overlay images credit by various artists. |
    <%= link_to 'Privacy Policy', privacy_path %>
  </p>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-36684515-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="col-md-8 col-sm-8 col-xs-8">
    <h3>
      Huawei, Ireland
    </h3>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-4">
    <span class="pull-right">
      <h1>
        <% if current_user %>
          <small>
            <%= current_user[:name] %><br/>
            <p><%= link_to 'Logout', logout_path, method: :delete %></p>
          </small>
          <%= image_tag current_user[:image_url], width: 50, align: 'right' %>
        <% end %>
      </h1>
    </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#BestFansInTheWorld!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div id="fb-root"></div>
  <div class="container" id="wrapper">
    <header>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
    </header>

    <div id="content"><%= yield %></div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/overlay/index.html.erb
<div class="well"><center>
	<h1>Irish Fans!</h1>
	<h3>Show that you are one of the <a href="#">#BestFansInTheWorld!</a></h3>
	<br>
	<h5>Update your Facebook to show your support!</h5>
	<h2><a href="#">#COYBIG</a></h2>

	<br>
  	<p><%= link_to "Login with Facebook", auth_provider_url, class: 'btn btn-success btn-lg' %></p>
  	<br>
</center></div>

app/views/overlay/privacy.html.erb
<h3>NP Profile Image Overlay - Privacy Policy</h3>

<p>This privacy policy has been compiled to better serve those who are concerned with how their
‘Personally identifiable information’ (PII) is being used online.
PII, as used in US privacy law and information security, is information that can be used on its
own or with other information to identify, contact, or locate a single person,
or to identify an individual in context. Please read this privacy policy carefully to get a
clear understanding of how this website collect, use, protect or otherwise handle your
Personally Identifiable Information.</p>

<h4>What personal information do we collect from the people that visit our website?</h4>
<p>When ordering or registering on our site, as appropriate, you may be asked
  to enter your name, email address, mailing address or other details to help you with your experience.</p>

<h4>When do we collect information?</h4>
<p>We collect information from you when you use our website or enter information on our site.</p>

<h4>How do we use your information?</h4>
<p>
  We may use the information we collect from you when you register on our website, or use certain other site features in the following ways:
  <ul>
    <li>To personalize user’s experience and to allow us to deliver the type of content and product offerings in which you are most interested.</li>
    <li>To improve our website in order to better serve you.</li>
    <li>To allow us to better service you in responding to your customer service requests.</li>
  </ul>
</p>

<h4>How do we protect visitor information?</h4>
<p>
  Our website is scanned on a regular basis for security holes and known vulnerabilities in order to make your visit to our site as safe as possible.
  We use regular Malware Scanning.
  Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.
  We implement a variety of security measures when a user places an order enters, submits, or accesses their information to maintain the safety of your personal information.
  All transactions are processed through a gateway provider and are not stored or processed on our servers.
</p>

<h4>Do we use ‘cookies’?</h4>
<p>We do not use cookies for tracking purposes</p>
<p>You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser’s Help menu to learn the correct way to modify your cookies.
If you disable cookies off, some features will be disabled that make your site experience more efficient and some of our services will not function properly.
However, you can still place orders.</p>

<h4>Third Party Disclosure</h4>
<p>We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information unless we provide you with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others’ rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.
Third party links
Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.
Google
Google’s advertising requirements can be summed up by Google’s Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en
We use Google AdSense Advertising on our website.
Google, as a third party vendor, uses cookies to serve ads on our site. Google’s use of the DART cookie enables it to serve ads to our users based on their visit to our site and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>

<h4>We have implemented the following:</h4>
<ul>
  <li>Google Display Network Impression Reporting</li>
  <li>Demographics and Interests Reporting</li>
</ul>
<p>We along with third-party vendors, such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions, and other ad service functions as they relate to our website.
  Opting out:
  Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising initiative opt out page or permanently using the Google Analytics Opt Out Browser add on.</p>

<h4>California Online Privacy Protection Act</h4>
<p>CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. – See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf</p>

<h4>According to CalOPPA we agree to the following:</h4>
<p>
  Users can visit our site anonymously.
  Once this privacy policy is created, we will add a link to it on our home page, or as a minimum on the first significant page after entering our website.
  Our Privacy Policy link includes the word ‘Privacy’, and can be easily be found on the page specified above.
  Users will be notified of any privacy policy changes:
      • On our Privacy Policy Page
  Users are able to change their personal information:
      • By emailing us
</p>

<h4>How does our site handle do not track signals?</h4>
<p>We honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.</p>

<h4>Does our site allow third party behavioral tracking?</h4>
<p>It’s also important to note that we do not allow third party behavioral tracking</p>

<h4>COPPA (Children Online Privacy Protection Act)</h4>
<p>When it comes to the collection of personal information from children under 13, the Children’s Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, the nation’s consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children’s privacy and safety online.
We do not specifically market to children under 13.</p>

<h4>Fair Information Practices</h4>
<p>The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.</p>
<p>In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:
We will notify the users via email</p>
<ul>
  <li>Within 7 business days</li>
</ul>
<p>We also agree to the individual redress principle, which requires that individuals have a right to pursue legally enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or a government agency to investigate and/or prosecute non-compliance by data processors.</p>

<h4>CAN SPAM Act</h4>
<p>The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.
We collect your email address in order to:</p>
<ul>
  <li>Send information, respond to inquiries, and/or other requests or questions.</li>
  <li>Process orders and to send information and updates pertaining to orders</li>
  <li>We may also send you additional information related to your product and/or service.</li>
  <li>Market to our mailing list or continue to send emails to our clients after the original transaction has occurred</li>
</ul>

<p>To be in accordance with CANSPAM we agree to the following:</p>
<ul>
  <li>NOT use false, or misleading subjects or email addresses</li>
  <li>Identify the message as an advertisement in some reasonable way</li>
  <li>Include the physical address of our business or site headquarters</li>
  <li>Monitor third party email marketing services for compliance, if one is used.</li>
  <li>Honor opt-out/unsubscribe requests quickly</li>
  <li>Allow users to unsubscribe by using the link at the bottom of each email</li>
</ul>
<p>&nbsp;</p>

app/views/overlay/profile.html.erb
<p>Create your <a href="#">#BestFansInTheWorld</a> profile images. Click on Publish button to directly upload the picture to Facebook or download the image to upload manually.</p>

<p>&nbsp;</p>

<div class="row">
  <% @overlay_images.each do |image|  %>
    <div class="col-md-3 col-sm-6 col-xs-12 pdbtm-sm">
      <p><%= image_tag "https://s3.amazonaws.com/profile-overlay-assets/#{current_user.uid}_#{image}",
              class: 'img-responsive', data: {action: 'zoom'} %></p>
      <div class="row">
        <div class="col-md-6 col-sm-6">
          <%= link_to 'Publish', publish_path(image: image.split('.').first),
              class: 'btn btn-primary btn-block', target: '_blank' %>
        </div>
        <div class="col-md-6 col-sm-6">
          <%= link_to 'Download', download_path(image: image.split('.').first),
              class: "btn btn-success btn-block" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= link_to "Facebook Login", '/auth/facebook' %>